[package]
name = "ring_buffer"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8"

[dev-dependencies]
num_cpus = "1.17"
rstest = "0.26"
