
[package]
name = "ring_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8.15"

[dev-dependencies]
num_cpus = "1.15.0"
rstest = "0.18.2"
